import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";
import { ClerkProvider } from "@clerk/nextjs";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{
		rel: "icon",
		url: "/favicon.ico"
	}],
};

export default function RootLayout({children, modal,}:
Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
			<html lang="en">
				<body className={`font-sans ${GeistSans.variable} flex flex-col gap-4`}>
					<TopNav/>
					{children}
					{modal}
					<div id="modal-root"/>
				</body>
			</html>
		</ClerkProvider>
	);
}
